version: '3.8'

services:
  db:
    build: ./db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - policy-link-network

  api:
    build: ./api
    environment:
      DATABASE_DSN: "host=db port=5432 user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB_NAME} sslmode=disable TimeZone=America/New_York"
    ports:
      - "1738:1738"
    depends_on:
      - db
    networks:
      - policy-link-network

networks:
  policy-link-network:
    driver: bridge